=== meetunix/einkaufszettel-server/src/main/resources/ezschema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Einkaufszettel",
    "description": "JSON representation of a Einkaufszettel",
    "type": "object",
    "required": ["eid", "created", "modified", "name", "version", "items"],
    "additionalProperties": false,
    "properties": {
        "eid" : {   "type": "string",
                    "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        },
        "created":  {   "type":     "integer",
                        "minimum":  1591606149464,
                        "maximum":  2095884000000
        },
        "modified": {    "type":    "integer",
                        "minimum":  1591606149464,
                        "maximum":  2095884000000
        },
        "name":     {   "type":     "string",
                        "pattern":  "^.{2,32}$"
        },
        "version":  {   "type":     "integer",
                        "minimum":  1
        },
        "items":    {   "type": "array",
                        "minItems": 1,
                        "maxItems": 128,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": ["iid", "itemName", "ordinal", "amount", "size", "unit", "catDescription", "catColor"],
                                "properties": {
                                    "iid" :             {   "type":     "string",
                                                            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
                                    },
                                    "itemName" :        {   "type":     "string",
                                                            "pattern":  "^.{2,48}$"
                                    },
                                    "ordinal" :         {   "type":     "integer",
                                                            "minimum":  1,
                                                            "maximum":  128
                                    },
                                    "amount" :          {   "type":     "integer",
                                                            "minimum":  1,
                                                            "maximum":  2147483647
                                    },
                                    "size" :            {   "type":     "number",
                                                            "minimum":  0,
                                                            "maximum":  32768
                                    },
                                    "unit" :            {   "type":     "string",
                                                            "pattern":  "^.{1,16}$"
                                    },
                                    "catDescription" :  {   "type":     "string",
                                                            "pattern":   "^.{2,64}$"
                                    },
                                    "catColor" :        {   "type":     "string",
                                                            "pattern":  "^[a-fA-f0-9]{6}$"
                                    }

                            }
                    }
            }

    }
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-09.json
{
 "eid": "bafbadd4-c583-4981-a223-1463c3d59b10",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 4950",
 "version": 1,
 "items": [
  {
   "iid": "42d2242b-efcd-4183-b5c4-e810dfc8af9a",
   "itemName": "some Item 6026",
   "ordinal": 9,
   "size": 115.01,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b5a5d551-1487-4669-8861-aff1fd4caa98",
   "itemName": "some Item 2681",
   "ordinal": 6,
   "size": 45.3,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "0656ec02-0591-47fe-a44d-8416aa263195",
   "itemName": "some Item 1186",
   "ordinal": 7,
   "size": 92.86,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "7c38be23-cb6c-45ff-b02d-60a936abfa55",
   "itemName": "some Item 4933",
   "ordinal": 2,
   "size": 150.64,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "2f531f47-9cec-4f57-8e59-cfd994f9f4ec",
   "itemName": "some Item 3418",
   "ordinal": 9,
   "size": 5.64,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f2914cad-4961-48c0-b2f7-47244a31d551",
   "itemName": "some Item 7636",
   "ordinal": 5,
   "size": 102.98,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "db8db98f-0a2f-486c-9b74-7eda0310db19",
   "itemName": "some Item 2079",
   "ordinal": 10,
   "size": 92.18,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "8bf9c085-ca06-464c-bd4e-988b7fad7ab7",
   "itemName": "some Item 8200",
   "ordinal": 2,
   "size": 173.71,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "a87a2e1d-e2aa-490a-b1dd-b57f211b8f02",
   "itemName": "some Item 8501",
   "ordinal": 1,
   "size": 20.33,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "87851230-ff23-4888-b24d-2465f6eb3a8e",
   "itemName": "some Item 9647",
   "ordinal": 6,
   "size": 110.2,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "916b03ff-7873-4cb2-8a3f-a748f3af171e",
   "itemName": "some Item 6923",
   "ordinal": 2,
   "size": 97.29,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "0e13d69e-f294-4c1a-9f45-751c6a7c53d8",
   "itemName": "some Item 2878",
   "ordinal": 3,
   "size": 161.76,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "edc8b13d-8036-49b3-ac2b-e9f80d2d2ebb",
   "itemName": "some Item 8402",
   "ordinal": 4,
   "size": 70.94,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "3db57772-113d-49fc-8054-9f0ab355bb3b",
   "itemName": "some Item 9011",
   "ordinal": 1,
   "size": 98.53,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "4d54ebd1-3fc2-49f9-afb3-28933362560e",
   "itemName": "some Item 7670",
   "ordinal": 1,
   "size": 88.24,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "e041c7ff-119c-4e96-aa62-48c1e574fdb3",
   "itemName": "some Item 4526",
   "ordinal": 4,
   "size": 158.03,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "8b67de35-8d7d-4133-9079-771288bde63a",
   "itemName": "some Item 4152",
   "ordinal": 5,
   "size": 84.01,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "c89e42d5-5944-400b-82aa-efce26cfea09",
   "itemName": "some Item 2863",
   "ordinal": 2,
   "size": 28.57,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "df7701f2-f0cc-45e5-8aca-ec112bb45cf1",
   "itemName": "some Item 5520",
   "ordinal": 10,
   "size": 152.27,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "34643599-8198-4481-a7d5-09e2b4e4386c",
   "itemName": "some Item 2735",
   "ordinal": 7,
   "size": 155.39,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "1b794140-9d1e-428e-941d-83ae0f907f8a",
   "itemName": "some Item 8634",
   "ordinal": 9,
   "size": 106.26,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "c500c70b-a238-4e3a-af32-d911ee8b72dc",
   "itemName": "some Item 1584",
   "ordinal": 10,
   "size": 92.45,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "6c31af1d-000d-49d5-8cbd-207d569e0467",
   "itemName": "some Item 1698",
   "ordinal": 6,
   "size": 92.24,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "85671b32-94c5-4550-a200-163439c6229c",
   "itemName": "some Item 7701",
   "ordinal": 1,
   "size": 29.6,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "bb08a7e0-2ed2-4549-8be0-fb4ffb235b56",
   "itemName": "some Item 2266",
   "ordinal": 6,
   "size": 34.18,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "91d778c9-bd6d-44d5-b58c-e05f434f2267",
   "itemName": "some Item 3330",
   "ordinal": 3,
   "size": 28.89,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "28732539-2dad-45f8-bd8f-3867c8e2faad",
   "itemName": "some Item 8072",
   "ordinal": 7,
   "size": 38.38,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "00199445-a59c-430b-b5e9-dbf74e56439e",
   "itemName": "some Item 3223",
   "ordinal": 8,
   "size": 65.39,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 898",
   "catColor": "A0B8FF"
  },
  {
   "iid": "4411ffa7-2274-4fe5-b1f2-dc700a24314e",
   "itemName": "some Item 5473",
   "ordinal": 6,
   "size": 8.12,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 361",
   "catColor": "A0B8FF"
  },
  {
   "iid": "230a3125-2587-4d86-8485-58683fb0737c",
   "itemName": "some Item 4555",
   "ordinal": 10,
   "size": 174.51,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  },
  {
   "iid": "451631d2-9b8b-4ea0-b80a-7228316dd301",
   "itemName": "some Item 9562",
   "ordinal": 4,
   "size": 34.6,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 782",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-04.json
{
 "eid": "fe6cc8c7-a948-42df-be7f-5c761fbdf78e",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 1736",
 "version": 1,
 "items": [
  {
   "iid": "ffe393fa-e7e4-4499-861a-ab32e36c33d6",
   "itemName": "some Item 8318",
   "ordinal": 4,
   "size": 154.61,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 327",
   "catColor": "A0B8FF"
  },
  {
   "iid": "493d4132-8e81-4e62-ac21-0e97e5a69555",
   "itemName": "some Item 5799",
   "ordinal": 2,
   "size": 62.14,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 279",
   "catColor": "A0B8FF"
  },
  {
   "iid": "6e629f90-bc46-491a-8313-e7a04dd6abfe",
   "itemName": "some Item 1651",
   "ordinal": 6,
   "size": 155.2,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 279",
   "catColor": "A0B8FF"
  },
  {
   "iid": "3b91d83a-ff31-40a1-848c-f796798773c1",
   "itemName": "some Item 1591",
   "ordinal": 9,
   "size": 85.1,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 820",
   "catColor": "A0B8FF"
  },
  {
   "iid": "8e6580a9-9a51-4148-9d30-0b916fcb1f29",
   "itemName": "some Item 8225",
   "ordinal": 1,
   "size": 174.23,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 327",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-00.json
{
 "eid": "18aede70-a704-449d-a23f-ece30998ab34",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 7874",
 "version": 1,
 "items": [
  {
   "iid": "6617dfbe-8010-4cbd-8c1b-740e86e27e01",
   "itemName": "some Item 6418",
   "ordinal": 6,
   "size": 123.37,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 433",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b5f8e32c-5cb1-490d-b526-646d55e75fe7",
   "itemName": "some Item 4829",
   "ordinal": 7,
   "size": 28.38,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 433",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-03.json
{
 "eid": "053a00c4-42f8-4632-8dd4-40179a66ea0a",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 1842",
 "version": 1,
 "items": [
  {
   "iid": "f87566e5-e735-437d-9d28-50b98dbd101e",
   "itemName": "some Item 2542",
   "ordinal": 3,
   "size": 99.11,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 963",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b3afc185-2a71-4b13-b61f-44dc4a654cb0",
   "itemName": "some Item 5645",
   "ordinal": 6,
   "size": 5.82,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 664",
   "catColor": "A0B8FF"
  },
  {
   "iid": "a3d897d7-8ee5-40f8-a3d6-71c6f1fd063f",
   "itemName": "some Item 3653",
   "ordinal": 9,
   "size": 182.4,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 664",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-02.json
{
 "eid": "aeb6c57f-49a1-4b46-88ee-ca45c0053bbc",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 8796",
 "version": 1,
 "items": [
  {
   "iid": "c429efc9-4e9a-4cfb-bef5-e021278be857",
   "itemName": "some Item 4226",
   "ordinal": 7,
   "size": 130.09,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "1546dfc9-2576-441d-9e93-59977b060a9e",
   "itemName": "some Item 6118",
   "ordinal": 3,
   "size": 28.5,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "aa598419-ac5a-4488-a03f-8c123e19e366",
   "itemName": "some Item 4919",
   "ordinal": 9,
   "size": 129.36,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "507bed84-5a33-4151-8488-f2a5d4ea3be8",
   "itemName": "some Item 7825",
   "ordinal": 3,
   "size": 140.67,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "a15bdb14-f018-42c0-ad33-12e44bb7b8f8",
   "itemName": "some Item 7179",
   "ordinal": 3,
   "size": 185.02,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "1f482604-0e15-4d3d-832a-d840b7f0f082",
   "itemName": "some Item 6145",
   "ordinal": 8,
   "size": 154.23,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "419bfebf-24e5-46ab-8a7e-5325af2781b7",
   "itemName": "some Item 4271",
   "ordinal": 3,
   "size": 10.52,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "6754e643-8a1b-4aab-91e2-258ff4ef2f52",
   "itemName": "some Item 1165",
   "ordinal": 1,
   "size": 157.6,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b4b1c299-d2ca-464d-86f2-11f95bad32db",
   "itemName": "some Item 4022",
   "ordinal": 7,
   "size": 26.57,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f2344ebb-9818-4fd9-bcba-826e9d9f46f2",
   "itemName": "some Item 5679",
   "ordinal": 3,
   "size": 39.95,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "6440cc24-f03d-4761-84a0-1cbeb0eb129a",
   "itemName": "some Item 8753",
   "ordinal": 4,
   "size": 161.47,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "12571bcb-7c00-4c4d-a0ce-3a64be9eb6cf",
   "itemName": "some Item 3033",
   "ordinal": 10,
   "size": 152.73,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "268ef175-02c4-480d-b36a-0c3be4b94247",
   "itemName": "some Item 1590",
   "ordinal": 3,
   "size": 154.06,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "727e758c-0d1b-471d-94ff-0718ec35cf2e",
   "itemName": "some Item 9117",
   "ordinal": 7,
   "size": 153.64,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "7c5c992c-e9a0-43a8-9c70-55d8528e17ca",
   "itemName": "some Item 4537",
   "ordinal": 10,
   "size": 30.59,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "e46724f4-e943-44cc-881f-7e4511e3b6c4",
   "itemName": "some Item 8727",
   "ordinal": 10,
   "size": 23.9,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f74cac91-302b-4483-9ec1-367d6f1e9d5c",
   "itemName": "some Item 2144",
   "ordinal": 1,
   "size": 8.77,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "4a972784-2ef8-479e-9ae2-8bb06dfe3cb5",
   "itemName": "some Item 4434",
   "ordinal": 2,
   "size": 27.65,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "e95232f0-f3ac-4da5-b48f-63c7ce4448e7",
   "itemName": "some Item 1576",
   "ordinal": 10,
   "size": 18.48,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "2db47393-1477-4604-b957-4b91cebff75e",
   "itemName": "some Item 6277",
   "ordinal": 4,
   "size": 124.49,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "ea23abfe-f4f6-4920-b17e-dcb14e9922f3",
   "itemName": "some Item 9172",
   "ordinal": 9,
   "size": 109.31,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "2fc11878-f0a1-4ce1-811c-d705a421f391",
   "itemName": "some Item 3901",
   "ordinal": 3,
   "size": 154.52,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "454d9f58-b764-48c0-b6de-18429585dc84",
   "itemName": "some Item 5916",
   "ordinal": 3,
   "size": 52.64,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "8174bc48-8f9a-441d-b8b4-c84ab78a7a99",
   "itemName": "some Item 9721",
   "ordinal": 2,
   "size": 66.28,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 293",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f6c8dfba-6fb7-4ffb-8112-fac877f11c07",
   "itemName": "some Item 6628",
   "ordinal": 7,
   "size": 68.78,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "698b7d59-8126-4484-9cb2-a51665215b6d",
   "itemName": "some Item 6684",
   "ordinal": 1,
   "size": 71.81,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "c1c3a9a9-254c-469e-a0b8-8abd9c1d9bfe",
   "itemName": "some Item 2033",
   "ordinal": 3,
   "size": 180.35,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f8a442fb-030c-4bd2-b564-f02f822eccd1",
   "itemName": "some Item 8792",
   "ordinal": 8,
   "size": 60.08,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "9ae4dda9-dd7c-456b-a705-cdc4c7c0fb42",
   "itemName": "some Item 1714",
   "ordinal": 7,
   "size": 1.09,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "c48f77db-5d44-4365-a5d1-87bf9719bff6",
   "itemName": "some Item 1192",
   "ordinal": 10,
   "size": 57.24,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  },
  {
   "iid": "720a78fc-6a8d-42d5-8043-5379bbb5b4ad",
   "itemName": "some Item 4134",
   "ordinal": 2,
   "size": 89.14,
   "amount": 8,
   "unit": "Kg",
   "catDescription": "description 734",
   "catColor": "A0B8FF"
  },
  {
   "iid": "0ed743eb-2183-49cf-8b46-4b2e130cec51",
   "itemName": "some Item 2068",
   "ordinal": 6,
   "size": 61.62,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 519",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-01.json
{
 "eid": "6d72f704-ffc4-44a8-aaf3-aac99b90174d",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 8680",
 "version": 1,
 "items": [
  {
   "iid": "6ade538b-da6c-4ca0-888f-09d8a3316556",
   "itemName": "some Item 1928",
   "ordinal": 10,
   "size": 62.75,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "0fcd0c35-e159-445c-ad39-1833dc492157",
   "itemName": "some Item 2396",
   "ordinal": 9,
   "size": 184.95,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "6059e0e9-c0d7-4fab-8ad1-9e0f72140e6c",
   "itemName": "some Item 1558",
   "ordinal": 1,
   "size": 181.88,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 161",
   "catColor": "A0B8FF"
  },
  {
   "iid": "a9c42a72-7de7-4ee9-aca7-736f42b1f596",
   "itemName": "some Item 8403",
   "ordinal": 8,
   "size": 50.0,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 161",
   "catColor": "A0B8FF"
  },
  {
   "iid": "972979e9-3e4f-400c-8255-3645ad1daa48",
   "itemName": "some Item 3797",
   "ordinal": 10,
   "size": 35.15,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 405",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b90d994d-6c14-4f07-ae45-593aa5ddd52e",
   "itemName": "some Item 8021",
   "ordinal": 5,
   "size": 145.21,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "0a8dae1a-1cf9-4a7d-8680-7727c4efae8e",
   "itemName": "some Item 8453",
   "ordinal": 3,
   "size": 30.8,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 161",
   "catColor": "A0B8FF"
  },
  {
   "iid": "130fa5de-67e5-4863-8ea7-7bcb11e79174",
   "itemName": "some Item 9806",
   "ordinal": 6,
   "size": 101.35,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "7e6aa5d4-a0f0-4e5d-b906-3061e9fcbc85",
   "itemName": "some Item 2255",
   "ordinal": 9,
   "size": 107.74,
   "amount": 6,
   "unit": "Kg",
   "catDescription": "description 405",
   "catColor": "A0B8FF"
  },
  {
   "iid": "4e2e8c0d-45a4-4409-b02b-26572b068115",
   "itemName": "some Item 7253",
   "ordinal": 3,
   "size": 35.97,
   "amount": 3,
   "unit": "Kg",
   "catDescription": "description 405",
   "catColor": "A0B8FF"
  },
  {
   "iid": "ee179395-c4d9-4605-8fb3-44d62ff6dc4f",
   "itemName": "some Item 7452",
   "ordinal": 8,
   "size": 112.19,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "cae85392-f0d6-415e-afcf-cb57801d3fcd",
   "itemName": "some Item 5926",
   "ordinal": 2,
   "size": 167.1,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "f20524e4-9d7d-442a-9e57-7cdacc654f86",
   "itemName": "some Item 2887",
   "ordinal": 6,
   "size": 143.76,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 405",
   "catColor": "A0B8FF"
  },
  {
   "iid": "af9bc347-708b-45e5-913e-8ea4bbb267ac",
   "itemName": "some Item 4908",
   "ordinal": 10,
   "size": 192.43,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 985",
   "catColor": "A0B8FF"
  },
  {
   "iid": "d0891750-98e8-4287-a9ad-308bf69146b1",
   "itemName": "some Item 9062",
   "ordinal": 4,
   "size": 197.97,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 405",
   "catColor": "A0B8FF"
  },
  {
   "iid": "16c4bdae-f06a-42ea-8925-2310687ad6be",
   "itemName": "some Item 6242",
   "ordinal": 4,
   "size": 116.76,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 161",
   "catColor": "A0B8FF"
  },
  {
   "iid": "2f9b25d8-3393-4175-bdf8-ab18fb5ae5b5",
   "itemName": "some Item 9608",
   "ordinal": 3,
   "size": 133.78,
   "amount": 7,
   "unit": "Kg",
   "catDescription": "description 161",
   "catColor": "A0B8FF"
  }
 ]
}

=== meetunix/einkaufszettel-server/test-tools/delete_example.json
{
  "eid" : "76f2c9e4-ea57-4df6-bdbf-cc7a5301df80",
  "created" : 1591694647793,
  "modified" : 1591694647793,
  "name" : "Mein Einkaufszettel",
  "version" : 9,
  "items" : [ {
    "iid" : "0d2426e7-69fc-44cd-8347-474594730a6d",
    "itemName" : "Feiner Alter",
    "ordinal" : 1,
    "amount" : 1,
    "size" : 0.7,
    "unit" : "l",
    "catDescription" : "Spirituosen",
    "catColor" : "E600FF"
  }, {
    "iid" : "852b8bfd-cfe0-4cec-b353-564049c3558e",
    "itemName" : "Emmentaler",
    "ordinal" : 1,
    "amount" : 1,
    "size" : 200.0,
    "unit" : "g",
    "catDescription" : "Milchprodukt",
    "catColor" : "FF00FF"
  }, {
    "iid" : "d6df2a92-5061-4efa-a28b-b849bf6e0ac9",
    "itemName" : "Russian Standard",
    "ordinal" : 2,
    "amount" : 100,
    "size" : 1.5,
    "unit" : "liter",
    "catDescription" : "Alkohol",
    "catColor" : "989898"
  } ]
}

=== meetunix/einkaufszettel-server/test-tools/examples/ez-06.json
{
 "eid": "39296a8d-bb49-4908-9296-bf00f712afb0",
 "created": 1687379479000,
 "modified": 1687379479000,
 "name": "ez-tool EZ 7919",
 "version": 1,
 "items": [
  {
   "iid": "135f6b73-082a-4d25-8781-fca78b5409c1",
   "itemName": "some Item 2196",
   "ordinal": 10,
   "size": 8.03,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 745",
   "catColor": "A0B8FF"
  },
  {
   "iid": "7f89efdb-4544-4e60-837a-4fe1f8eecdad",
   "itemName": "some Item 3396",
   "ordinal": 5,
   "size": 124.81,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 750",
   "catColor": "A0B8FF"
  },
  {
   "iid": "cd357612-0c24-4238-ae8b-6b70dd8cb420",
   "itemName": "some Item 6434",
   "ordinal": 2,
   "size": 174.4,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 745",
   "catColor": "A0B8FF"
  },
  {
   "iid": "e6cdcc82-d1c5-4148-85dd-659a244c4ee0",
   "itemName": "some Item 2855",
   "ordinal": 8,
   "size": 62.19,
   "amount": 2,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "1ccdf93d-9cd6-4416-9292-2011fab9c085",
   "itemName": "some Item 3417",
   "ordinal": 3,
   "size": 164.19,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 745",
   "catColor": "A0B8FF"
  },
  {
   "iid": "522ab231-4da9-47c3-9ff6-cb3d89cd79f9",
   "itemName": "some Item 9682",
   "ordinal": 3,
   "size": 137.34,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "49d2421c-ccd2-4428-b2bc-8265daee3df0",
   "itemName": "some Item 5188",
   "ordinal": 10,
   "size": 151.65,
   "amount": 10,
   "unit": "Kg",
   "catDescription": "description 745",
   "catColor": "A0B8FF"
  },
  {
   "iid": "5cfed39f-56bd-4606-9222-9b20eef3924e",
   "itemName": "some Item 6388",
   "ordinal": 3,
   "size": 188.87,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b1cdf60d-fb1e-4873-b368-998685301c8a",
   "itemName": "some Item 7083",
   "ordinal": 8,
   "size": 44.56,
   "amount": 5,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "b8844c4c-8dd1-44c9-ba19-ebeecf0bb6be",
   "itemName": "some Item 5713",
   "ordinal": 4,
   "size": 22.27,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 750",
   "catColor": "A0B8FF"
  },
  {
   "iid": "4b2f5704-184f-458d-a878-0423792e35d5",
   "itemName": "some Item 6985",
   "ordinal": 5,
   "size": 107.41,
   "amount": 4,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "1ec6d617-7c9f-4456-9e7b-7d8992ffed28",
   "itemName": "some Item 8925",
   "ordinal": 10,
   "size": 87.8,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "177c56ad-3d9e-4f49-a923-32a5e494a954",
   "itemName": "some Item 3393",
   "ordinal": 3,
   "size": 160.03,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "01e6f963-b96f-4d88-a26d-96d583bbb435",
   "itemName": "some Item 6345",
   "ordinal": 2,
   "size": 36.66,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  },
  {
   "iid": "7989b28e-4a99-4bb0-83e3-402c84666d20",
   "itemName": "some Item 5693",
   "ordinal": 3,
   "size": 65.23,
   "amount": 1,
   "unit": "Kg",
   "catDescription": "description 745",
   "catColor": "A0B8FF"
  },
  {
   "iid": "74391cdc-e389-477f-adb2-b49964a1d074",
   "itemName": "some Item 7703",
   "ordinal": 8,
   "size": 148.73,
   "amount": 9,
   "unit": "Kg",
   "catDescription": "description 119",
   "catColor": "A0B8FF"
  }
 ]
}
